### ISSUE TITLE
Remove small white borders around items in client page (and maybe elsewhere)

### ISSUE THREAD

**Issue by komali2** [508-dev/508.dev#9]
Client page, and maybe other places, has weird super thin white border. Get rid of. 

![Image](https://user-images.githubusercontent.com/8533113/223336895-0cc1860b-f691-4868-94b8-f2a1264c4585.png)

**Comment by Figgy24-20** [comment]
Should I remove the white border every page that has it, or only on the Clients page?

It's based on some css:
`section.index {`
**`  border: 1px solid var(--color-lightGrey); `**
`  border-radius: 2px;`
`  margin: var(--margin-big);`
`}`

**Comment by komali2** [comment]
All pages that have it
